#!/bin/zsh
default_sessionname="Odin"
if [ -z $2 ]; then
    SESSIONNAME=${default_sessionname}
else
    SESSIONNAME=$2
fi
tmux has-session -t $SESSIONNAME &> /dev/null

if [ $? != 0 ]; then
    tmux new-session -s ${SESSIONNAME} -d
    #tmux send-keys -t $SESSIONNAME "~/home/scripts/otmux" C-m 
    tmux new-window -k -t ${SESSIONNAME}:1 -n base

    tmux new-window -k -t ${SESSIONNAME}:2 -n svn
    tmux send-keys -t ${SESSIONNAME}:2 "cd ~/dev/svn" C-m

    tmux new-window -k -t ${SESSIONNAME}:3 -n engines
    tmux send-keys -t ${SESSIONNAME}:3 "cd ~/dev/git/madhouse/mhengines/madhouse6/trunk/ss3" C-m

    tmux new-window -k -t ${SESSIONNAME}:4 -n arch
    tmux send-keys -t ${SESSIONNAME}:4 "cd ~/dev/git/madhouse/architect" C-m
fi

tmux attach -t $SESSIONNAME
